// Sample data for testing CRUD operations
// This would normally be used to seed the database

export const samplePets = [
  {
    name: "Buddy",
    type: "dog" as const,
    breed: "Golden Retriever", 
    age: "adult" as const,
    gender: "male" as const,
    size: "large" as const,
    weight: 30,
    color: "Golden",
    description: "Friendly and energetic dog who loves playing fetch and swimming. Great with families and children.",
    story: "Buddy was found as a stray but has shown incredible resilience and love for humans. He's looking for a family who can give him the active lifestyle he deserves.",
    images: ["/placeholder.svg?height=400&width=400&text=Buddy"],
    vaccinated: true,
    neutered: true,
    microchipped: true,
    houseTrained: true,
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: false,
    specialNeeds: false,
    specialNeedsDescription: null,
  },
  {
    name: "Whiskers",
    type: "cat" as const,
    breed: "Siamese",
    age: "young" as const,
    gender: "female" as const,
    size: "medium" as const,
    weight: 4,
    color: "Cream and brown",
    description: "Elegant and vocal cat who loves attention and conversation. Very intelligent and playful.",
    story: "Whiskers came to us when her elderly owner could no longer care for her. She's looking for someone who appreciates her chatty personality.",
    images: ["/placeholder.svg?height=400&width=400&text=Whiskers"],
    vaccinated: true,
    neutered: true,
    microchipped: true,
    houseTrained: true,
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: true,
    specialNeeds: false,
    specialNeedsDescription: null,
  },
  {
    name: "Luna",
    type: "cat" as const,
    breed: "Ragdoll",
    age: "adult" as const,
    gender: "female" as const,
    size: "large" as const,
    weight: 6,
    color: "Blue point",
    description: "Gentle and laid-back cat who enjoys being held and petted. Perfect lap cat for quiet evenings.",
    story: "Luna is a gentle soul who came to us after her family moved overseas. She's looking for a calm home where she can be the center of attention.",
    images: ["/placeholder.svg?height=400&width=400&text=Luna"],
    vaccinated: true,
    neutered: true,
    microchipped: true,
    houseTrained: true,
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: true,
    specialNeeds: false,
    specialNeedsDescription: null,
  },
  {
    name: "Charlie",
    type: "dog" as const,
    breed: "Beagle",
    age: "young" as const,
    gender: "male" as const,
    size: "medium" as const,
    weight: 15,
    color: "Tri-color",
    description: "Curious and energetic beagle who loves exploring and sniffing around. Great with other pets.",
    story: "Charlie was surrendered by his previous family due to apartment restrictions. He needs a home with a yard where he can explore safely.",
    images: ["/placeholder.svg?height=400&width=400&text=Charlie"],
    vaccinated: true,
    neutered: false,
    microchipped: true,
    houseTrained: false,
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: true,
    specialNeeds: false,
    specialNeedsDescription: null,
  },
  {
    name: "Snowball",
    type: "rabbit" as const,
    breed: "Holland Lop",
    age: "baby" as const,
    gender: "female" as const,
    size: "small" as const,
    weight: 1,
    color: "White",
    description: "Adorable baby rabbit who loves fresh vegetables and gentle handling. Perfect for first-time rabbit owners.",
    story: "Snowball was part of an accidental litter and is looking for a loving home where she can grow up safely.",
    images: ["/placeholder.svg?height=400&width=400&text=Snowball"],
    vaccinated: true,
    neutered: false,
    microchipped: false,
    houseTrained: false,
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: false,
    specialNeeds: false,
    specialNeedsDescription: null,
  }
]